data:
  transform:
    input_size: 128
    ToTensor: True
    Normalize: True
  dataloader:
    dataset: abstract_art_512
    data_root: './dataset/abstract_art_512/'
    batch_size: 4
    shuffle: True
    num_workers: 8
    drop_last: True

training:
  model: GAN
  epoch: 1000
  lrG: 0.0002
  lrD: 0.0002
  beta1: 0.5
  beta2: 0.999

log:
  save_dir: './saved/out/'
  log_dir: './saved/log'